### ISSUE TITLE
Snmp Comms Error

### ISSUE THREAD

**Issue by samcqdx** [disisto/apc-switched-rack-pdu-control-panel#2]
Hi there @disisto 
Having problems connecting via snmp to pdu  using your code , i have tried using your troubleshooting coms test but am not able to get that going even...were am i going wrong ,cant get hold of you via any other channels .

What i did try:
Tested snmp coms with this little programme - that worked(image below)
Even disabled security settings - 'Authnopriv' to see if that helped- stil no joy. 

I like the gui and would even like to request a few changes could help testing too for this home project, for a a fee of course...if its possible.

Please note im a newbee to this(old timer trying to learn some php) , 
Using windows 10, Xamp with apache2 and sql.... as web server .
hope you can help out , some screen shots below

Any help will be appreciated
Thanks
Sam

These are my pdu config details (passphrases edited for security reasons)
####  Set your personal APC PDU settings

$apcPDUs = [];

$apcPDUs['001'] = createPDUCfg(
  true,                           // Toggle Switch             :: Switch on (true) or switch off (false) to stop monitoring the PDU.
  '10.1.1.30',
  'SNMPuser',
  'tfxxxxxxxxxxxxxx29',
  'MD5',
  'tfxxxxxxxxxxxxx35c',
  'DES',
  'noAuthNoPriv'                              // Security Level            :: Set desired security level: noAuthNoPriv | authNoPriv | authPriv | More detail: https://www.php.net/manual/en/function.snmp3-get.php
);

![image](https://github.com/disisto/apc-switched-rack-pdu-control-panel/assets/8448617/ff5b0da0-b8d0-4254-a7ed-15535487d86c)
![image](https://github.com/disisto/apc-switched-rack-pdu-control-panel/assets/8448617/ed860ee5-d037-4e93-8ab5-91820217fddc)
![image](https://github.com/disisto/apc-switched-rack-pdu-control-panel/assets/8448617/7ad3f9fd-f5cf-43ad-b7d3-5f65161097b8)
![image](https://github.com/disisto/apc-switched-rack-pdu-control-panel/assets/8448617/3e8126c2-2082-4d53-9a3e-81200749e6d0)

**Comment by disisto** [comment]
Hi Sam,

As you may have noticed in the [server configuration](https://github.com/disisto/apc-switched-rack-pdu-control-panel/wiki#server-configuration)/[troubleshooting](https://github.com/disisto/apc-switched-rack-pdu-control-panel/wiki#troubleshooting) section, the focus is on Linux-based systems. I have no experience with Windows-based XAMPP systems.

The error message "PHP Fatal error: Unexpected error: Calling an undefined function snmp3_walk() in [...]" indicates that ```php-snmp``` is not installed or not activated.

If I remove ```php-snmp``` support on my test machine, I get the same error message:
![image](https://github.com/disisto/apc-switched-rack-pdu-control-panel/assets/77121158/925fab90-befe-4262-b51a-f31476e023f4)

Just create a file ```phpinfo.php``` with the content:
```
<?= phpinfo(); ?>
```

If SNMP for PHP is installed, you will find this section, once you opened phpinfo.php via your web browser:
![image](https://github.com/disisto/apc-switched-rack-pdu-control-panel/assets/77121158/c03ac215-5c5f-4f36-b243-3b258d3c0126)

If SNMP for PHP is not installed, this section will be missing.

Based on your screenshot, your XAMPP installation is located at ```C:\xampp```. Ideally, your php.ini should be located in the following path: ```C:\xampp\php\php.ini```. 

Look for ```;extension=snmp``` (it might be commented out with a semicolon) and remove the semicolon to enable the extension. If it is not present, add this line. Restart the XAMPP server after you have saved the php.ini with the change.

If the ```phpinfo.php``` still does not show the activation of SNMP, then make sure that the extension ``php_snmp.dll`` is located in the following folder: ```C:\xampp\php\ext\```.
If it is not the right folder, the ```php.ini``` will tell you where the extensions are located. Look for the following line ```extension_dir =```.

Information is based on a Google search, so I can't promise that the paths mentioned match the paths you use.

With the current information, this should be it.

Personal recommendation: SNMPv3 brings encryption that was not available in previous versions. Therefore I would suggest to switch the setting from ```noAuthNoPriv```to ```authPriv```, once the troubleshooting is done.

Good luck and enjoy the script!

**Comment by samcqdx** [comment]
Hi @disisto 
Thank you so much for the pointers, after those points you mentioned i was able to get the GUI up and running but was only able to read info from the pdu ,but not action any of the power off/on commands , took a few hours on that .

Eventually i reinstalled the whole lot uploaded your php file - an it all worked !!!
Thank you so very much for this wonderful GUI, it is a god sent .

Would you be willing to make changes to your code v1.3??

1.Having a few other buttons on the GUI apart from these were i can group example:

Group 1>> Button would toggle any combination of outputs together (output 1,4,6,7,8)- on/off/reboot
Group 2>> Button would toggle any combination of outputs together (output 2,4)- on/off/reboot
Group 3>> Button would toggle any combination of outputs together (output 2,4,8)- on/off/reboot

2.Would you be able to add a section on the GUI  were you could setup a New Pdu with all connection details and a connect option   (ip, username ,...) instead of having to modify the php file every time?

Im willing to do some testing for you if you have the time and patience  for something  like this , let me know , await your reply .

Sam

**Comment by disisto** [comment]
Hi Sam,

Allow me to provide you with some context about myself and the projects I've made available to help you better understand what to expect here.

Personally, I am not a programmer/developer/software engineer. Sometimes, I face challenges that can only be solved by using a script, which does not make me a programmer, as any professional programmer would confirm after reviewing the source code.

When I publish a project on GitHub, it means that I have delved deeply into a specific topic (for this project: SNMP protocol) and have completed it for my own needs. Currently, my repertoire includes over 200 such projects that are much larger and more complex. Since 99% of all projects are based on open source, I believe it's important to present the end product to the community when circumstances allow. I find the concept of different people facing the same challenges and working together to find a solution rather than each working individually quite appealing. Before diving into a subject, I look online (mostly on GitHub) to see if and how other people have solved various challenges. Nothing bothers me more personally than existing projects that are either undocumented or have insufficient documentation. Therefore, I have a personal commitment not to publish a project online unless there is documentation for it.

Ironically, with the release of v1.3 for this project, I made a change that actually requires an update to the documentation. I haven't done that (yet). This principle prevents me from publishing various projects online or providing updates, but it doesn't stop me from continuing to develop them internally. In short, some projects/functions will never be published online because documentation would require extra effort that is not feasible given the quantity and complexity of projects. I'm talking about my personal free time, as I'm involved in other topics professionally.

This project had been on my to-do list for a long time and gained higher priority when I had to run my test lab from home due to the first COVID lockdown. Leaving all devices powered on or manually turning them on/off was not an option. One of the tasks was to figure out how to conveniently scan an NFC tag with a smartphone to turn the required device on and off as needed. This task required an API that the APC PDU didn't offer. Why am I telling you this? Because 3/4 of my projects are APIs, just like this one. The web interface is only a byproduct that assists me in developing the API. The web interface is not actually the end product or the main function.

When you hover over the outlet icon with your mouse, you'll notice that a URL is displayed. If you enter this URL in your web browser, you'll notice that it controls the corresponding outlet.

<img src="https://github.com/disisto/apc-switched-rack-pdu-control-panel/assets/77121158/156850f6-c2df-40e4-a4d6-843ed1c8cefd" width="300" alt="edit_automation">

Now, if you create an automation using the Apple app "Shortcuts" and specify this URL as the endpoint, you can control the outlet with the program of your choice without any programming knowledge. Whether it's Apple's "Shortcuts," an alternative for Android, a service like IFTTT, a voice assistant like Alexa/Google Assistant, or something you develop yourself, you can control the outlet using the script without the need for a web interface.

In my case, most devices have an NFC tag that is controlled via Apple "Shortcuts."

<img src="https://github.com/disisto/apc-switched-rack-pdu-control-panel/assets/77121158/49159b81-a48e-44e3-b50f-b8d59baf9351" width="300" alt="edit_automation">
<img src="https://github.com/disisto/apc-switched-rack-pdu-control-panel/assets/77121158/397e397a-5b60-4b46-bacf-05c5d1dda052" width="300" alt="actions">



To answer point 1 of your question:

- My goal was never to replicate the existing web interface of APC. The function to control groups is already offered in the APC interface. For example, I have various device groups that are turned off on a schedule (30 minutes after work).
- If you follow my example with Apple "Shortcuts," you could replicate this function by specifying multiple endpoints (Never tested it myself.).  Whether it's scheduled or triggered by your choice is up to you.

To answer point 2 of your question:

- I operate PDUs in different VLANs. These are isolated from each other and cannot communicate with each other. Therefore, I have a personal commitment to keep the script "portable." This means I run one script per VLAN, which receives the corresponding access credentials for the PDUs. Before publishing, I had initially stored the data in a MySQL database. Since I would have had to operate a database per VLAN, this was quite an overhead for what was actually needed. A non-existent database doesn't need monitoring or updates. Backing up a single file is much easier than backing up a database. Thus, the current solution is easier to install and requires less maintenance, making it the preferred solution.
- One could create a file containing a form (e.g., edit.php) to edit another file containing access credentials (e.g., config.php) and read these through the main file (index.php). I only insert the access credentials into the script once, which raises the question of why it would be necessary to replace this process with a GUI. Why would one need to change the access credentials regularly or use the GUI more than once?

Regarding the note that the current status after triggering a button through the GUI does not reflect the current/changed status, I also noticed this when using the GUI last time. It is already on my to-do list among many other things and will be addressed in one of the future versions. This may require the use of web technologies like AJAX alongside PHP. It doesn't seem to be a syntax error but rather the way the status is determined after a reload. This requires more attention and thus more time.

As I mentioned before, the project itself is completed for my needs. It's far from perfect, but it has been serving its purpose for 3 years. Improvement suggestions are always welcome and should be submitted via a Pull Request. I am open to expanding the script if it adds value. If someone has a different direction in mind, they are welcome to fork the project and steer it in the desired direction.

**Comment by samcqdx** [comment]
Thank you for all the tips, i do share your ''concept of different people facing the same challenges and working together ...'' i did notice the link with details on the GUI and will use it to further this all.
Once again i thank you for this small project it has opened many doors.
Look forward to any further updates and developments .
:-)
